### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by FabianHofmann** [FRESNA/powerplantmatching#1]
![countrytotals](https://cloud.githubusercontent.com/assets/19226431/20011650/a654e858-a2ac-11e6-93a2-2ed0e938f642.jpg)
![entsoe_stats](https://cloud.githubusercontent.com/assets/19226431/20011652/a67e12f0-a2ac-11e6-97e1-dacc3399c946.jpg)
![fueltypetotals](https://cloud.githubusercontent.com/assets/19226431/20011651/a67d0766-a2ac-11e6-97a2-a03febdefa05.jpg)
![matching_proportions](https://cloud.githubusercontent.com/assets/19226431/20011654/a683952c-a2ac-11e6-8ce8-8e4982fb18d1.jpg)
![hydroclassification](https://cloud.githubusercontent.com/assets/19226431/20104077/e0534900-a5cc-11e6-8d3f-002756cc8110.jpg)
![modulstruct](https://cloud.githubusercontent.com/assets/19226431/20449087/984dc0c2-ade7-11e6-96e0-f1169c9a7fef.png)
![powerplants](https://cloud.githubusercontent.com/assets/2552981/20465688/b7b9d2c0-af63-11e6-964e-2f0a19d26f15.png)

**Comment by FabianHofmann** [comment]
![powerplantmap](https://user-images.githubusercontent.com/19226431/31497088-1ed25900-af5e-11e7-8da7-9ff76fe18c3e.png)
![matching_proportions](https://user-images.githubusercontent.com/19226431/31497124-45ea4b10-af5e-11e7-8153-7046f17ca05f.png)

**Comment by FabianHofmann** [comment]
![modulstruct_rotated](https://user-images.githubusercontent.com/19226431/31513014-2feef76e-af8d-11e7-9b4d-f1be929e2dba.png)

**Comment by FabianHofmann** [comment]
[PowerplantmatchingDoc.pdf](https://github.com/FRESNA/powerplantmatching/files/1380529/PowerplantmatchingDoc.pdf)

**Comment by FabianHofmann** [comment]
![powerplantmap_without_wepp](https://user-images.githubusercontent.com/19226431/43488643-ada49010-951a-11e8-844b-6625e5e9ac5e.png)

**Comment by coroa** [comment]
The pictures and plots tracked in this issue are licensed under a [Creative Commons Attribution 4.0 International license (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/). They are attributed to (Frankfurt Institute for Advanced Studies)[https://www.fias.science/de/theoretische-physik/gruppen/stefan-schramm/fresna/], the original version is available from the (powerplantmatching)[https://github.com/FRESNA/powerplantmatching] repository.
