### ISSUE TITLE
TypeError in extended_by_non_matched

### ISSUE THREAD

**Issue by dcradu** [FRESNA/powerplantmatching#14]
I am running the module from a custom config file. Basically, I am selecting AT as target country and {Natural Gas, Hydro, Wind} as target fuel types. Main point, I am trying to obtain subsets of the already existing database.

I am importing the config file as:
`config = pm.get_config(path_to_config)`

And I call the powerplants module as:
`plants = pm.powerplants(config, from_url=False, stored=False)`

The following error pops up, with the printed (and trimmed to 5 elements only) lists being `included_ids` defined in the `extended_by_non_matched` function:

`INFO:powerplantmatching.collection:Collect combined dataset for ENTSOE, GEO, GPD, JRC, OPSD`
`['OEU5814', 'OEU5717', 'OEU5816', 'OEU5815', 'OEU5809']`
`INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'OPSD'.`
`['H284', 'H242', 'H174', 'H225', 'H194']`
`INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'JRC'.`
`['14W-BFR-KW-----A', '14W-TZG-KW-----H', '14W-BYP-KW-----6', '14W-BWM-KW-----L', '14W-TZR-KW-----I']`
`INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'ENTSOE'.`
`0`

`TypeError: only list-like objects are allowed to be passed to isin(), you passed a [int]`

As can be seen, there is an `int` popping up in (what I think is) the aggregation of the matched database with extra elements from one of the reliable sources. Could this be caused by my approach in getting customized results?

**Comment by FabianHofmann** [comment]
Sorry for the late reply, I've overseen it. Is the problem still existent with the newer version? Or did you find a solution?

**Comment by FabianHofmann** [comment]
I think this error is solved in the current version. I closing this, feel free to open again if the error still occurs

**Comment by dcradu** [comment]
Sorry for the very late reply. The initial error was not occurring on an Ubuntu distribution, just on my Windows machine. Couldn't find an explanation for it, tough. Thank you for following up. If we encounter it again, we'll report it.

**Comment by FabianHofmann** [comment]
alright :)
