### ISSUE TITLE
Issue with reloading and rematching

### ISSUE THREAD

**Issue by Jaspergeipel** [FRESNA/powerplantmatching#17]
Setting from_url=False (default) apparently does not load again all the necessary data files.
Adding update_all= True  doesn't work either.
How to rerun the whole scripting after adapting the manual config file?

**Comment by FabianHofmann** [comment]
Hey thank you for pointing this out! I fixed it (I least I think). Can you test the new pip version (conda update takes a bit) or the actual master branch?

**Comment by Jaspergeipel** [comment]
yep, update=all works, as well as "update_all_matches.py" in maching analysis. Many thanks
