### ISSUE TITLE
Aggregate_units() does not work

### ISSUE THREAD

**Issue by Strohut** [FRESNA/powerplantmatching#21]
Hello,

I've been trying to run the "Example of use.ipynb" and everything works fine except for aggregate_units(), which leads to the error message below.

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-a18a659aafe9> in <module>
----> 1 dfs = [geo.powerplant.aggregate_units(), entsoe.powerplant.aggregate_units()]
      2 intersection = pm.matching.combine_multiple_datasets(dfs)

~\Anaconda3\lib\site-packages\powerplantmatching\cleaning.py in aggregate_units(df, dataset_name, pre_clean_name, save_aggregation, country_wise, use_saved_aggregation, config)
    339         if country_wise:
    340             duplicates = pd.concat([duke(df.query('Country == @c'))
--> 341                                     for c in df.Country.unique()])
    342         else:
    343             duplicates = duke(df)

~\Anaconda3\lib\site-packages\powerplantmatching\cleaning.py in <listcomp>(.0)
    339         if country_wise:
    340             duplicates = pd.concat([duke(df.query('Country == @c'))
--> 341                                     for c in df.Country.unique()])
    342         else:
    343             duplicates = duke(df)

~\Anaconda3\lib\site-packages\powerplantmatching\duke.py in duke(datasets, labels, singlematch, showmatches, keepfiles, showoutput)
    109 
    110         run = sub.Popen(args, stderr=sub.PIPE, cwd=tmpdir, stdout=stdout,
--> 111                         universal_newlines=True)
    112         _, stderr = run.communicate()
    113 

~\Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    773                                 c2pread, c2pwrite,
    774                                 errread, errwrite,
--> 775                                 restore_signals, start_new_session)
    776         except:
    777             # Cleanup if the child failed starting.

~\Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1176                                          env,
   1177                                          os.fspath(cwd) if cwd is not None else None,
-> 1178                                          startupinfo)
   1179             finally:
   1180                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by FabianHofmann** [comment]
Hey @Strohut, thanks for reporting. The example works fine for me. However I'm on a linux machine. It seems that your temporary directory is not accessible. Although it is very unlikely, that the error comes from there, but can you try out the following (in python):

```python
import tempfile
tempfile.mkdtemp()
```
And have a look if this returned folder exists

**Comment by Strohut** [comment]
Thanks for the quick answer! The code returns `'C:\\Users\\<>\\AppData\\Local\\Temp\\tmpkkql0cul'` so I don't think that is where the problem lies. Do you have any other advice for what I could try?

**Comment by FabianHofmann** [comment]
mmh this turns out to be tricky for me. The question where I'm stuck is which file it cannot be found/opened. 

Can you please try the following: 
1. In the notebook, after the error occurs, go into debug mode (type `%debug` in the next cell)
2. Print the cwd with `p cwd`. This is the directory where the aggregation is supposed to happen, if cwd is not defined go up in the traceback, type `u` and then try again
3. Outside of python: go into this directory and check which files are in it.

**Comment by Strohut** [comment]
Okay I tried it and while the debugger shows a folder, there is no such directory on my computer if I go to check.

**Comment by FabianHofmann** [comment]
what is the name of the folder? is it a tempdir?

**Comment by Strohut** [comment]
Yes, the folder it shows is
> 'C:\\Users\\<>\\AppData\\Local\\Temp\\tmp_gpt1nn5'

**Comment by FabianHofmann** [comment]
Okay I think we're getting closer. It seems, that the tempdir is either not properly created or does not have the correct rights or is somehow deleted too early. 

Can you again check the rights of the folder coming out of 
```python
import tempfile
tempfile.mkdtemp()
```

**Comment by Strohut** [comment]
I'm not certain what you mean but all permissions except for Special Permissions are checked and for the attributes, it states that they are Read-only (Only applies to files in folder).

**Comment by FabianHofmann** [comment]
Yes thanks, this is what I meant. Another thing what came up in my mind. 
In debug mode, can you go 2 times up, and print out `datasets`. It might be that this is empty, and this causes an error.

**Comment by FabianHofmann** [comment]
Ah this might be the error: Do you have java installed ? just go into the terminal and type in `java`  or `java -version`. Does this raise an error?

**Comment by Strohut** [comment]
If I enter debut mode above this part of the code, it says that datasets is not defined. But it shows the results for all of the variables that I did define in the code.
And no, I don't have java installed. Is it necessary?

**Comment by FabianHofmann** [comment]
yes that will be it, java has to be installed. Probably I insert a warning if it's not installed.

**Comment by Strohut** [comment]
Thanks a lot, that was it!
