### ISSUE TITLE
Raise error if java not installed

### ISSUE THREAD

**Issue by FabianHofmann** [FRESNA/powerplantmatching#22]
Ths code check whether java is installed. Not having it installed, lead to confusion especially on windows machines where the resulting error is very opaque

**Comment by ChinCity** [comment]
When unzipping the local file I got this (see below), lacking 'duke'. I assume it is related to this thread (sorry if not). It's not clear, should I download duke or Java? and how?

![image](https://user-images.githubusercontent.com/37304682/86098786-e52d8000-bab6-11ea-9c0c-e88bb28144b2.png)

**Comment by FabianHofmann** [comment]
Did you check whether java is installed? Duke comes automatically with the powerplantmatching package

**Comment by ChinCity** [comment]
I have java installed.

Version 8 update 131 (build 1.8.0_131-b11)
