### ISSUE TITLE
Add datasets to custom configuration

### ISSUE THREAD

**Issue by FebinKa** [FRESNA/powerplantmatching#24]
Hi,

How can I add additional datasets to a custom configuration of the yaml? And where should I save the modified file for the changes to be applied?

**Comment by FabianHofmann** [comment]
Okay let's try to write a small instruction (this should go to the README afterwards)

# Intergrating new Datasets
Let's say you have a new dataset "FOO.csv" which you want to combine with the other data bases. For properly integrating it, please follow these steps. Please, before starting, make sure that you've installed `powerplantmatching` from your downloaded local repository (link). 

1. Look where `powerplantmatching` stores all data files
    ```python 
    import powerplantmatching as pm
    pm.core.package_config['data_dir']
    ```
2. Store FOO.csv in this directory under the subfolder `data/in`. So on Linux machines the total path under which you store your data file would be:
    `/home/<user>/.local/share/powerplantmatching/data/in/FOO.csv`
3. Look where `powerplantmatching` looks for a custom configuration file 
    ```
    pm.core.package_config['custom_config']
    ```
4. If this file does not exist on your machine, download the [standard configuration](https://raw.githubusercontent.com/FRESNA/powerplantmatching/master/powerplantmatching/package_data/config.yaml) and store it under the given path.
5. Open the yaml file and add a new entry under the section `#data config`.
    The new entry should look like this 
    ```yaml
    FOO:
      reliability_score: 4
      fn: FOO.csv
    ```
    The `reliability_score` indicates the reliability of your data, chose a number between 1 (very bad data) and 7 (very good data). If the data is openly available, you can add a `url` argument which will enable automatic downloading
6. Add 'FOO' to the `matching_sources` in your yaml file, that it looks somewhat like this 
    ```yaml
    #matching config
    matching_sources:
        ...
        - OPSD
        - FOO
    ``` 
7. Add a function `FOO()` to the data.py in the powerplantmatching source code. You find the file in your local repository under `powerplantmatching/data.py`. The function should be structured like this:

    ```python
    def FOO(raw=False, config=None):
        """
        Importer for the FOO database.
    
        Parameters
        ----------
        raw : Boolean, default False
            Whether to return the original dataset
        config : dict, default None
            Add custom specific configuration,
            e.g. powerplantmatching.config.get_config(target_countries='Italy'),
            defaults to powerplantmatching.config.get_config()
        """
        config = get_config() if config is None else config
        df = parse_if_not_stored('FOO', config=config)
        if raw:
            return geo
        df = make_some_cleaning_with(df)
        return df
    ```
    Note that `make_some_cleaning_with(df)` is just a placeholder for the code your raw data into into the standard format. Note that here you should make sure that the data gets the standard column names (as given by `pm.get_config()['target_columns']`)
8. Test your function with 
    ```python
    pm.data.FOO()
    ```
    and make sure the FOO entry is given in the configuration 
    ```python
    pm.get_config()
    ```

9. If everything works fine, you can run the whole matching process with 
    ```python
    pm.powerplants(update_all=True)
    ```
If you have the feeling that this is worth sharing, please make a Pull Request and help `powerplantmatching` to improve!

**Comment by FabianHofmann** [comment]
@Strohut can you try this out and check where things are not clear? It;s quiet a few points, also happy about proposition to make the process easier.

**Comment by Strohut** [comment]
Great, thanks a lot for the detailed explanation! 
I have started working on your explainer in a fork and expanded a bit on the 7th step, but I wanted to wait to submit a Pull Request before I can get every part of the guide to work. I managed to add a new dataset but step 9 results in `ValueError: No objects to concatenate`. 
The hardest part for me was to get an idea of what I had to do in the `data.py`. I got a ValueError with the new dataset when trying to combine it with the JRC dataset. However, I saw that all other examples in the file except for these two included a column name and it worked when I added that. I think highlighting which elements are mandatory in step 7 would make it even easier to use, but it's already possible to find whatever is necessary from the other examples in `data.py`.

**Comment by FebinKa** [comment]
I've been trying to resolve the error in step 9 again but without success. Even when I try to run the code in a new environment and with the original config.yaml, I obtain the following error. 

![grafik](https://user-images.githubusercontent.com/55534006/78927722-a67fbf00-7a9f-11ea-9bf4-8a7287299bb2.png)

**Comment by FabianHofmann** [comment]
It seems as the df.query('Country == @c') is empty. Can you double check fully included sources in your config. The error happens when ppm wants to extend (fully include) one of those datasets. If your new dataset is there I guess, there has to be something wrong with the country names?

**Comment by FabianHofmann** [comment]
For those cases it's always good to `%debug` and traceback which dataset caused the error. Go up to the first trace and print out `source[name]`

**Comment by FebinKa** [comment]
Yes, one of the country names in my new dataset was "Czechia" instead of "Czech Republic", thank you! 
However, I still cannot add all of my datasets, most of which include information on only one country. I can combine different datasets as long as they have some geographic overlap, but when I try to combine datasets from different countries, I obtain the following error message as it tries to compare them and finds no matching entries at all. (The upper half is specific to the update_all function but the last three errors apply whenever I want to do anything with datasets from different countries)

![grafik](https://user-images.githubusercontent.com/55534006/79135367-84dc4b80-7daf-11ea-91e4-084d58ab4537.png)

**Comment by FabianHofmann** [comment]
Hey @FebinKa , is the issue still there? If not I'm closing this

**Comment by FebinKa** [comment]
Hi, I found a work around that allowed me to do what I wanted to but I think the original issue of not being able to match datasets if they have no overlap (geographic in my case) might still exist.

**Comment by FabianHofmann** [comment]
Alright, I think setting country_wise to `false` should do it or? (Even though this is not the best workaround for this case)
