### ISSUE TITLE
Downloading collection matched data I get 'TypeError'

### ISSUE THREAD

**Issue by ChinCity** [FRESNA/powerplantmatching#27]
When I attempt to download the processed power plant data I get a TypeError. 
I have verified my pandas version and it is 0.23.4, the dependency for the powerplantmatching of pandas is 0.23.0 or greater. So it should be fine...

Code: 

`import powerplantmatching as pm
import pandas as pd

all_data = pm.collection.matched_data()`

Error:

`
  File "C:\Users\sab\AppData\Local\Continuum\anaconda3\lib\site-packages\powerplantmatching\cleaning.py", line 290, in mode
    return x.mode(dropna=False).at[0]

TypeError: mode() got an unexpected keyword argument 'dropna'
`

**Comment by FabianHofmann** [comment]
Hey @ChinCity ,

thank you for reporting. Unfortunately it seems that the requirement are wrong in this case. The dropna flag was introduced in pandas v0.24, see [its doc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mode.html). So we have to update the dependencies.

**Comment by ChinCity** [comment]
Thank you
