### ISSUE TITLE
How do I know the integration of a new dataset was successful

### ISSUE THREAD

**Issue by ChinCity** [FRESNA/powerplantmatching#28]
Hi, 

I followed your instructions Integrating a new dataset:

In the last step I got this: 

    In[9]
    pm.data.JRC_OPEN_UNITS()
    INFO:numexpr.utils:NumExpr defaulting to 4 threads.

    Out[9]
    Empty DataFrame
    Columns: [Name, Fueltype, Technology, Set, Country, Capacity, Efficiency, Duration, 
    Volume_Mm3, DamHeight_m, YearCommissioned, Retrofit, lat, lon, projectID]
    Index: []`

Before updating, is there a way to check what I have done? With an empty Index, i'm not sure what I have done is correct.

------------------------

It might be useful to include the function I added in the data.py:

def JRC_OPEN_UNITS(raw=False, config=None, update=False):

    config = get_config() if config is None else config

    df = parse_if_not_stored('JRC_OPEN_UNITS', update, config=config)
    if raw:
        return df
    return (df.rename(columns={'id': 'projectID',
                              'name_p': 'Name',
                              'capacity_p': 'Capacity',
                              'country': 'Country',
                              'type_g': 'Fueltype',
                              'lat': 'lat',
                              'lon': 'lon',
                              'year_commissioned':'YearCommissioned'})
            .loc[lambda df: df.Country.isin(config['target_countries'])]
            .replace(dict(Fueltype={'Fossil Gas': 'Natural Gas',
                                    'Fossil Coal-derived gas': 'Natural Gas',
                                    'Hydro Run-of-river and poundage': 'Hydro',
                                    'Hydro Pumped Storage': 'Hydro',
                                    'Hydro Water Reservoir': 'Hydro',
                                    'Fossil Hard coal': 'Hard Coal',
                                    'Fossil Hard Coal': 'Hard Coal',
                                    'Fossil Brown coal/Lignite': 'Lignite',
                                    'Fossil Oil': 'Oil',
                                    'Fossil Oil shale': 'Oil',
                                    'Wind Offshore': 'Wind',
                                    'Wind Onshore': 'Wind',
                                    'Biomass': 'Bioenergy',
                                    'Fossil Peat': 'Bioenergy',
                                    'Marine': 'Other'
                                    }))
            .drop(columns = ['name_g', 'capacity_g', 'NUTS2', 'status_g', 'year_decommissioned'])
            .powerplant.convert_alpha2_to_country()
            .pipe(set_column_name, 'JRC_OPEN_UNITS')
            .pipe(config_filter))

**Comment by FabianHofmann** [comment]
Hey @ChinCity, it looks quiet good. I think you have to pull the `convert_alpha2_to_country` line to the top before the country filtering. 

Or probably the line 
```
        .loc[lambda df: df.Country.isin(config['target_countries'])]
```
can be deleted as the config_filter should take care of this.

**Comment by ChinCity** [comment]
Hey @FabianHofmann, 

I tried both of those but I'm still getting an empty dataframe :/

**Comment by FabianHofmann** [comment]
Have you checked if your raw file is properly loaded? If yes, I would go step by step through the lines and check where the entries are dropped (atm it seems only the config filter could do so)

**Comment by ChinCity** [comment]
You are right that did it!

Final code: 

    config = get_config() if config is None else config

    change_fueltype={'Fossil Gas': 'Natural Gas',
                     'Fossil Coal-derived gas': 'Natural Gas',
                     'Hydro Run-of-river and poundage': 'Hydro',
                     'Hydro Pumped Storage': 'Hydro',
                     'Hydro Water Reservoir': 'Hydro',
                        'Fossil Hard coal': 'Hard Coal',
                        'Fossil Hard Coal': 'Hard Coal',
                        'Fossil Brown coal/Lignite': 'Lignite',
                        'Fossil Oil': 'Oil',
                        'Fossil Oil shale': 'Oil',
                        'Wind Offshore': 'Wind',
                        'Wind Onshore': 'Wind',
                        'Biomass': 'Bioenergy',
                        'Fossil Peat': 'Bioenergy',
                        'Marine': 'Other'}

    df = parse_if_not_stored('JRC_OPEN_update', update, config)
    if raw:
        return df
    df = (df.rename(columns={'eic_p': 'projectID',
                              'name_p': 'Name',
                              'capacity_p': 'Capacity',
                              'country': 'Country',
                              'type_g': 'Fueltype',
                              'lat': 'lat',
                              'lon': 'lon',
                              'year_commissioned':'YearCommissioned'})
       .loc[lambda df: df.Country.isin(config['target_countries'])]
        .replace(change_fueltype)
        .drop(columns = ['eic_g', 'name_g', 'capacity_g', 'NUTS2',
                         'status_g', 'year_decommissioned', 'type_g2'])
         .pipe(set_column_name, 'JRC_OPEN_update'))

    return df

**Comment by ChinCity** [comment]
You are right that did it!

Final code: 

    config = get_config() if config is None else config

    change_fueltype={'Fossil Gas': 'Natural Gas',
                     'Fossil Coal-derived gas': 'Natural Gas',
                     'Hydro Run-of-river and poundage': 'Hydro',
                     'Hydro Pumped Storage': 'Hydro',
                     'Hydro Water Reservoir': 'Hydro',
                        'Fossil Hard coal': 'Hard Coal',
                        'Fossil Hard Coal': 'Hard Coal',
                        'Fossil Brown coal/Lignite': 'Lignite',
                        'Fossil Oil': 'Oil',
                        'Fossil Oil shale': 'Oil',
                        'Wind Offshore': 'Wind',
                        'Wind Onshore': 'Wind',
                        'Biomass': 'Bioenergy',
                        'Fossil Peat': 'Bioenergy',
                        'Marine': 'Other'}

    df = parse_if_not_stored('JRC_OPEN_update', update, config)
    if raw:
        return df
    df = (df.rename(columns={'eic_p': 'projectID',
                              'name_p': 'Name',
                              'capacity_p': 'Capacity',
                              'country': 'Country',
                              'type_g': 'Fueltype',
                              'lat': 'lat',
                              'lon': 'lon',
                              'year_commissioned':'YearCommissioned'})
       .loc[lambda df: df.Country.isin(config['target_countries'])]
        .replace(change_fueltype)
        .drop(columns = ['eic_g', 'name_g', 'capacity_g', 'NUTS2',
                         'status_g', 'year_decommissioned', 'type_g2'])
         .pipe(set_column_name, 'JRC_OPEN_update'))

    return df
