### ISSUE TITLE
TypeError in duke.py

### ISSUE THREAD

**Issue by SimDeh** [FRESNA/powerplantmatching#3]
Hello,

I mentioned a TypeError in duke.py by running the code:
`TypeError: a bytes-like object is required, not 'str'`

in line 99:
`if 'Error' in stderr:
            raise RuntimeError("duke failed: {}".format(stderr))`

I could fix it by setting 'Error' as a byte instead of a string: 
`if b'Error' in stderr:
            raise RuntimeError("duke failed: {}".format(stderr))`

Best regards

**Comment by coroa** [comment]
Thanks for spotting, we're using python 2. Your fix is only partial, since stderr will still be a bytes object and then fail in
`raise RuntimeError("duke failed: {}".format(stderr))`

**Comment by coroa** [comment]
This is not fixed! It IS a problem with python 3.
