### ISSUE TITLE
Any untrapped NaN values in Technology cast to string "nan", then treated as matches by Duke

### ISSUE THREAD

**Issue by henri-chat-noir** [FRESNA/powerplantmatching#39]
I am not sure how confident I am that this is a 'bug' in the original code / combination of datasets, but I think worth reporting as at least a potential weakness.  The line that creates an issue, a potential one at least is:

.assign(**{col: df[col].astype(str) for col in ['Name', 'Country', 'Fueltype', 'Technology', 'Set', 'File']

which occurs in the aggregate_units function in Cleaning module.  If "nan" text saved out to input.csv that then is used by Duke, these values are seen as a match, thereby affecting the outcome probability score inappropriately.  Duke seems to want to see empty string/cells saved to CSV in order to (properly) ignore values as being 'missing'.

There is a coding style question as well as to whether type-enforcement should be confirmed earlier in the cleaning processing and/or whether this should be embededded as a fixed list of column names, particularly as the xml editing suggests that column names are able to be user-defined.

**Comment by henri-chat-noir** [comment]
Just to log in a quick follow-up, as I learn more about Pandas behavior.  It seems the default datatype may different across Pandas versions related to the str dtype now being available (and object being the default).  This may be an issue that could be cured by more explicit datatype assignment, but I haven't dug into it yet.

**Comment by FabianHofmann** [comment]
thanks @henri-chat-noir for reporting the nan issue is a very good point I haven't thought about. I try to tackle this potential issue in the next days.

**Comment by FabianHofmann** [comment]
this is solved in the most recent version, thanks for reporting
