### ISSUE TITLE
heuristics.py:58 - IndexingError

### ISSUE THREAD

**Issue by SimDeh** [FRESNA/powerplantmatching#4]
Hey guys,

while running the updated code I got the following Warning/Error:

> powerplantmatching/heuristics.py:58: UserWarning: Boolean Series key will be reindexed to match DataFrame index.extend_by = extend_by[extend_by_b]

> File"anaconda/envs/py35/lib/python3.5/sitepackages/pandas/core/indexing.py",line
>  1817, in check_bool_indexer raise IndexingError ('Unalignable boolean Series key provided')
> IndexingError: Unalignable boolean Series key provided

I tried to run the code with Python 2.7 as well as 3.5. I attached a screenshot of the error. 

Best regards
Simon 

![screen shot 2017-04-20 at 13 37 02](https://cloud.githubusercontent.com/assets/26626463/25228912/76eddbd8-25ce-11e7-9fca-4967377e464f.png)
![screen shot 2017-04-20 at 13 36 20](https://cloud.githubusercontent.com/assets/26626463/25228894/63d68b4e-25ce-11e7-9f67-88b2c0993ff6.png)

**Comment by SimDeh** [comment]
It seems that the problem is caused by choosing neither rawEU and rawDE data from OPSD in data.py

**Comment by coroa** [comment]
rawEU and rawDE are just there for debugging and should not be used in the final code. Reopening for confirmation.
