### ISSUE TITLE
Custom config path is never accessed

### ISSUE THREAD

**Issue by Eugenio2192** [FRESNA/powerplantmatching#41]
According to the instructions in the README to add a custom dataset  the package looks for custom configs in the directory returned by:

`pm.core.package_config['custom_config']`  

However, the get_config function never access this directory, it goes instead into "repo_data_dir".

Line 28 of he core.py:
```
    package_config = _package_data('config.yaml')
    custom_config = filename if filename else _package_data('custom.yaml')
```

I placed my custom config there, but I don´t think that´s intented to be like that.

**Comment by koen-vg** [comment]
I was also struggling with getting powerplantmatching to use my own config, and in the end also placed my configuration in `repo_data_dir/custom.yaml`.
It doesn't seem like `~/.powerplantmatching_config.yaml` has any effect, and it also doesn't seem like the `config` option for the `pm.powerplants` takes full effect.

Would a pull request with a suggestion for how to fix this be appreciated?

**Comment by Eugenio2192** [comment]
@koen-vg I just made a pull request, I did some local tests and it is working properly. If you don't want to wait for the merge just pull the core.py file from my fix-custom-config branch

**Comment by koen-vg** [comment]
Oh great! I'm in no particular hurry, but good to know :)

**Comment by FabianHofmann** [comment]
Please reopen if some unexpected behaviour reappears.
