### ISSUE TITLE
pm.powerplants(reduced=False) not working

### ISSUE THREAD

**Issue by Codingnoob94** [FRESNA/powerplantmatching#43]
Hello,

I'm very much new to python and programming in general. I tried to use the powerplantmatching for my research and installed it as described with "pip install powerplantmatching entsoe-py --no-deps" and
"conda install pandas networkx pycountry xlrd seaborn pyyaml requests matplotlib geopy beautifulsoup4 cartopy". But for some reason it doesn't seem to work properly. I'm using MacOS and program with python on Jupiter Notebook.
Now if I use "pm.powerplants(from_url=True)" it works and shows me the database, 
but if I use "pm.powerplants(reduced=False)" it shows me this error: 
"FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/z2/9bwgw7_x5pl5wwx_405s91t00000gn/T/tmpka0l6pr6/linkfile.txt' ". 

I hope you can help me with my issue.

**Comment by FabianHofmann** [comment]
Hey @Codingnoob94, could you send the whole error message? Sorry in advance, if this will take some days, I am a bit too buisy atm.

**Comment by Codingnoob94** [comment]
Thank you for your reply. No problem. Here is the error message:

INFO:powerplantmatching.collection:Collect combined dataset for CARMA, ENTSOE, GEO, GPD, JRC, OPSD
WARNING:powerplantmatching.collection:Forcing update since the cache file is missing
INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'CARMA'.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-11-03d1947bc975> in <module>
----> 1 pm.powerplants(reduced=False)

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/powerplantmatching/collection.py in matched_data(config, stored, update, update_all, from_url, extend_by_vres, extendby_kwargs, subsume_uncommon_fueltypes, **collection_kwargs)
    210     matching_sources = [list(to_dict_if_string(a))[0]
    211                         for a in config['matching_sources']]
--> 212     matched = collect(matching_sources, **collection_kwargs)
    213 
    214     if isinstance(config['fully_included_sources'], list):

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/powerplantmatching/collection.py in collect(datasets, update, use_saved_aggregation, use_saved_matches, reduced, custom_config, config, **dukeargs)
     96 
     97     if update:
---> 98         dfs = parmap(df_by_name, datasets)
     99         matched = combine_multiple_datasets(
    100             dfs, datasets, use_saved_matches=use_saved_matches, config=config,

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/powerplantmatching/utils.py in parmap(f, arg_list, config)
    348         return [x for i, x in sorted(res)]
    349     else:
--> 350         return list(map(f, arg_list))
    351 
    352 

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/powerplantmatching/collection.py in df_by_name(name)
     72                                    use_saved_aggregation=use_saved_aggregation,
     73                                    dataset_name=name,
---> 74                                    config=config)
     75         else:
     76             return df.assign(projectID=df.projectID.map(lambda x: [x]))

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/powerplantmatching/cleaning.py in aggregate_units(df, dataset_name, pre_clean_name, save_aggregation, country_wise, use_saved_aggregation, config)
    341         if country_wise:
    342             duplicates = pd.concat([duke(df.query('Country == @c'))
--> 343                                     for c in df.Country.unique()])
    344         else:
    345             duplicates = duke(df)

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/powerplantmatching/cleaning.py in <listcomp>(.0)
    341         if country_wise:
    342             duplicates = pd.concat([duke(df.query('Country == @c'))
--> 343                                     for c in df.Country.unique()])
    344         else:
    345             duplicates = duke(df)

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/powerplantmatching/duke.py in duke(datasets, labels, singlematch, showmatches, keepfiles, showoutput)
    127         if dedup:
    128             return pd.read_csv(os.path.join(tmpdir, 'linkfile.txt'),
--> 129                                encoding='utf-8', usecols=[1, 2], names=labels)
    130         else:
    131             res = pd.read_csv(os.path.join(tmpdir, 'linkfile.txt'),

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/pandas/io/parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    608     kwds.update(kwds_defaults)
    609 
--> 610     return _read(filepath_or_buffer, kwds)
    611 
    612 

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    460 
    461     # Create the parser.
--> 462     parser = TextFileReader(filepath_or_buffer, **kwds)
    463 
    464     if chunksize or iterator:

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    817             self.options["has_index_names"] = kwds["has_index_names"]
    818 
--> 819         self._engine = self._make_engine(self.engine)
    820 
    821     def close(self):

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1048             )
   1049         # error: Too many arguments for "ParserBase"
-> 1050         return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
   1051 
   1052     def _failover_to_python(self):

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1865 
   1866         # open handles
-> 1867         self._open_handles(src, kwds)
   1868         assert self.handles is not None
   1869         for key in ("storage_options", "encoding", "memory_map", "compression"):

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/pandas/io/parsers.py in _open_handles(self, src, kwds)
   1366             compression=kwds.get("compression", None),
   1367             memory_map=kwds.get("memory_map", False),
-> 1368             storage_options=kwds.get("storage_options", None),
   1369         )
   1370 

/opt/anaconda3/envs/Masterarbeit/lib/python3.7/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    645                 encoding=ioargs.encoding,
    646                 errors=errors,
--> 647                 newline="",
    648             )
    649         else:

FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/z2/9bwgw7_x5pl5wwx_405s91t00000gn/T/tmp3_2flzwr/linkfile.txt'

**Comment by Codingnoob94** [comment]
hello Fabian Hoffmann,

thank you for your effort. Fortunately I resolved my issue. 
I needed to install the java package in Anaconda. Now it works.
