### ISSUE TITLE
Possible bug: where is Wind in Italy?

### ISSUE THREAD

**Issue by FLomb** [FRESNA/powerplantmatching#47]
Hi, 

I noticed that, for some reason, your data show 0 wind power plants to exist in Italy, whereas Italy has about 10 GW of Wind power installed as of yet. Where is this wind gone? It seems strange, considering the variety of databases you use, that this issue occurs.

**Comment by kais-siala** [comment]
I think wind and solar are underreported here. I use the values from IRENA (which does not provide a geographical distribution), and distribute them myself depending on maps of capacity factors (and some randomness).

**Comment by fneum** [comment]
In fact, wind and solar are not matched at all.

More on the background why wind and solar are not included in the matching process in Section 2.4 of https://doi.org/10.1016/j.esr.2018.11.004

> Since especially wind and solar units are comparatively small in terms of unit-wise capacity (ranging from very-low kW to low MW scale), but huge in terms of deployed numbers (e.g. more than 1.7 million single units only in Germany [24]), they would massively impede the matching process. Moreover, since most of the single solar panels and wind turbines do not have a specific name (except larger wind and solar parks), there is no data in the name column and, consequently, no input for the string comparator available. Therefore, all wind and solar units are being filtered as part of the data mending, enabling us to keep the entire process computationally manageable.
>
> However, for a further usage of the derived power plant data in modelling approaches, PPM is able to concatenate given wind and solar units from the OPSD renewable data package [24] to the final dataset at the end of the matching process.

I think the mentioned concatenation works with

```py
pm.powerplants().powerplant.extend_by_VRE(base_year=2016)
```

judging from https://github.com/FRESNA/powerplantmatching/issues/11 but haven't used it since then (and might take some time).

Distributing by the capacity factor or by squared capacity factor is a valid heuristic that we also use over at PyPSA-Eur in spatial aggregation.

**Comment by FLomb** [comment]
Thanks for the comments. It looks like the extension you suggest leads to an Error on my machine:

`TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'`

**Comment by FabianHofmann** [comment]
> Thanks for the comments. It looks like the extension you suggests leads to an Error on my machine:
> 
> `TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'`

Cannot reproduce the mentioned error on the current master, feel free to reopen (or rather open another issue) if it still occurs.
