### ISSUE TITLE
simplify functions to use new functionality of entsoe-py

### ISSUE THREAD

**Issue by lisazeyen** [FRESNA/powerplantmatching#56]
as pointed out by @ericzhou571 [entsoe-py](https://github.com/EnergieID/entsoe-py) package has now a function to return directly a pandas DataFrame what could simplify the function [`def ENTSOE`](https://github.com/FRESNA/powerplantmatching/blob/bcae330adef96a795740fe146d8e5661fb14ed8e/powerplantmatching/data.py#L714)

**Comment by FabianHofmann** [comment]
done in current release
