### ISSUE TITLE
CSV Files missing

### ISSUE THREAD

**Issue by zoobar** [FRESNA/powerplantmatching#6]
installed the package but running any of the functions fails because of missing csv files. How to get hold of the required csvs would be very much appreciated.

**Comment by coroa** [comment]
You probably have not setup [git lfs](https://git-lfs.github.com/) correctly, which is responsible for fetching the files. If that is not the case, it would help us to narrow down the issue, if you included a bit more details about which csv files are missing.

Best,
Jonas

**Comment by zoobar** [comment]
Works now. Thanks a lot.

**Comment by coroa** [comment]
Good to hear.
