### ISSUE TITLE
License of the pictures

### ISSUE THREAD

**Issue by maledo** [FRESNA/powerplantmatching#7]
Hi,

thank you for sharing your powerplantmatching tool under an open license!
I was wondering, whether your pictures also get an open license to use them for talks and so on. In particular, I am interested in the comparison picture of https://github.com/FRESNA/powerplantmatching/issues/1#issuecomment-409376255.

Thank you!

**Comment by FabianHofmann** [comment]
Hello maledo, 
you can easily use the pictures for your purposes. If you want to recreate them, most of them are reproducible via the powerplantmatching.plot module. Anyway we are going to add a CC BY license for the pictures (which does not restrict your usage) and a reference which you can use.
Best regards!
Fabian

**Comment by maledo** [comment]
Great, thank you!

**Comment by coroa** [comment]
I added a note about their license to the respective thread:
https://github.com/FRESNA/powerplantmatching/issues/1#issuecomment-413840949
