### ISSUE TITLE
GEO and GPD links leading to bad gateway

### ISSUE THREAD

**Issue by davide-f** [FRESNA/powerplantmatching#73]
The Workflow in PyPSA-Africa is crashing because when ppl loads the GEO dataset, the corresponding link leads to bad gateway because the fias website where data are stored cannot be found. Link: https://vfs.fias.science/f/3f4cc3876f/?raw=1

Do you know whether this is permanent? Otherwise maybe a rehosting is needed?

**Comment by FabianHofmann** [comment]
Thank you @davide-f for reporting, I'll fix it.

**Comment by FabianHofmann** [comment]
oh it seems the server itself is down due to maintenance. I cannot update the link for now, let's wait till tomorrow if it is available again. Sorry for the inconvenience...

**Comment by davide-f** [comment]
It has been unavailable for about 4-5 days, but now it's back on.
I close the issue
