### ISSUE TITLE
ESE database not found

### ISSUE THREAD

**Issue by anyexingluzk** [FRESNA/powerplantmatching#9]
Hi,

When trying to compile for the first time, the ESE dataset is missing and both links suggested are invalid. Anyone can update the links please?

**Comment by coroa** [comment]
unfortunately the ESE page is 
> ... currently in process of transitioning the site.

If you are able to download any dataset from them (global csv or otherwise), please tell us how to, and we will update the instructions. In the mean time, use the attached [`projects.xls`](https://github.com/FRESNA/powerplantmatching/files/2921453/projects.zip) I downloaded from them somewhen in December.

**Comment by anyexingluzk** [comment]
Thank you for your reply. I managed to get what I wanted even without the project.xls. Nevertheless, it's good to have it so I can recompile it in the future.

**Comment by JanFrederickUnnewehr** [comment]
Energy Storage Exchange (ESE) database -> now DOE Global Energy Storage Database
The ESE website has changed there name and link.
new: https://www.energystorageexchange.org/
new project export side: https://www.energystorageexchange.org/projects

There are now using the csv. format for file export and some header names has also been changed compared to the old .xls export. Therefore the data import [(](https://github.com/FRESNA/powerplantmatching/blob/master/powerplantmatching/data.py) function "def ESE" does not work anymore. 

following some changes:
**CSV header**
old -- new
"Name" -- "Title"
"Technology Type" -- "Technology Broad Category" or "Technology Mid-Type" or "Technology Sub-Type"
"Technology Type Category 2" -- removed
"Commissioning Date" -- "Commissioned" (Some data has missing items or unusual format DD.05.YYYY)
"Rated Power in kW" -- "Rated Power"
